### PR TITLE
Expose subscriptions

### LINKED ISSUE #25: Feature request: Get subscribers count
Great library!
It would be useful to be able to get the number of subscriptions to an event (even better would be to get the subscriptions as a list, like in c# events: https://msdn.microsoft.com/en-us/library/system.delegate.getinvocationlist(v=vs.110).aspx).

Current workaround I'm using: `(dispatcher as any)._subscriptions.length`

### PR DESCRIPTION
**Pull request by tzachshabtay**
Expose subscriptions as a readonly array.
Resolves #25

### CODE REVIEW

**Comment by tzachshabtay** [comment]
Hmm, not sure why the build fails. It passes locally, but it seems that the dependencies aren't properly updated in Travis?

**Comment by KeesCBakker** [comment]
Look likes something is wrong on a signal dispatcher:

test/dispatcher-test.ts (27,23): Property 'subscriptions' does not exist on type 'SignalDispatcher'. Did you mean '_subscriptions'? (2551)
test/dispatcher-test.ts (34,23): Property 'subscriptions' does not exist on type 'SignalDispatcher'. Did you mean '_subscriptions'? (2551)

**Comment by tzachshabtay** [comment]
@KeesCBakker DispatcherBase has subscriptions:

https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/blob/acbecdb919d15ebf47848b1a924d35e44e5f7598/packages/ste-core/src/dispatching.ts#L88

And SignalDispatcher extends DispatcherBase, so it should have it.
Which is why, like I said earlier, the problem seems to be that the dependencies are not properly updated (the tests might still be using an older version of SignalDispatcer or something like that?).
I don't know how lerna works and how you've set it up to work with Travis to properly update the dependencies, which is why I've asked for your help in figuring this out.

**Comment by KeesCBakker** [comment]
I exposed a `.count` now. Should fix #25. I'm closing this pull request as it is not building in Travis.

Thanks for your efforts!

**Pull request closed without merging**
